Repository dlang/installer, pull requests merged in 2020-02, with the labels that each got.

#430 Windows installer: increase compressor dictionary size for smaller installer
  windows/d2-installer.nsi
Labels: auto-merge

#432 Windows installer: update proposed downloads from VS2017 to VS2019
  windows/d2-installer.nsi
  windows/vcinstall.ini
Labels: auto-merge

#433 fix Issue 20421 - Exceptions don't work when linking through lld-link
  windows/build_lld.bat
Labels: Bug Fix

#434 Use LLD with /SAFESEH:NO
  create_dmd_release/build_all.d
Labels: auto-merge

#428 [WIP] fix Issue 20489 - Installer deleting files after install
  windows/d2-installer.nsi
Labels: Enhancement, WIP

#425 build dmd.exe with LDC
  create_dmd_release/build_all.d
  create_dmd_release/create_dmd_release.d
  windows/build_release.bat
Labels: auto-merge

#444 install mingw-7.0.0-3.zip to add msvcr120.dll as mentioned in the changelog
  create_dmd_release/build_all.d
Labels: auto-merge
