Repository dlang/installer, pull requests merged in 2020-09, with the labels that each got.

#457 add auto-update for the d-keyring
  script/install.sh
Labels: auto-merge-squash

#467 Revert "add auto-update for the d-keyring (#457)"
  script/install.sh
Labels: auto-merge

#469 fix issue 20620 - dmd version has -dirty suffix
  create_dmd_release/create_dmd_release.d
Labels: Bug Fix

#297 Add '--dmd' and '--dc' to print the path of the installed compiler
  changelog/install-dmd-dc.dd
  script/install.sh
  test/common.sh
  test/t/where.sh
Labels: auto-merge

#468 Windows: Rename VSINSTALLDIR to LDC_VSDIR
  .azure-pipelines/build-winrelease.yml
  azure-pipelines.yml
  create_dmd_release/build_all.d
  create_dmd_release/create_dmd_release.d
  windows/build_release.bat
Labels: auto-merge-squash

#472 merge stable
  changelog/install-dmd-dc.dd
  changelog/ldc-built-releases.dd
  test/installation.sh
Labels: auto-merge
